name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkou code
      uses: actions/checkout@v4
      with: 
         fecth-depth: 0

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secretd.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secretd.DOCKER_PASSWORD }}
      run:
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando login"

    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
